# Latihan 6

In [1]:
import pandas as pd
import numpy as np

In [3]:
weather = pd.read_csv("weather_AUS.csv", sep=',')
weather

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
5       2008-12-06   Albury     14.6     29.7       0.2          NaN   
6       2008-12-07   Albury     14.3     25.0       0.0          NaN   
7       2008-12-08   Albury      7.7     26.7       0.0          NaN   
8       2008-12-09   Albury      9.7     31.9       0.0          NaN   
9       2008-12-10   Albury     13.1     30.1       1.4          NaN   
10      2008-12-11   Albury     13.4     30.4       0.0          NaN   
11      2008-12-12   Albury     15.9     21.7       2.2          NaN   
12      2008-12-13   Albury     15.9     18.6      15.6          NaN   
13      2008-12-14   Albury     12.6     21.0       3.6          NaN   
14      2008-12-15   Albury      8.4     24.6       0.0          NaN   
15      2008-12-16   Albury      9.8     27.7       NaN          NaN   
16      2008-12-17   Albury     14.1     20.9       0.0          NaN   
17      2008-12-18   Albury     13.5     22.9      16.8          NaN   
18      2008-12-19   Albury     11.2     22.5      10.6          NaN   
19      2008-12-20   Albury      9.8     25.6       0.0          NaN   
20      2008-12-21   Albury     11.5     29.3       0.0          NaN   
21      2008-12-22   Albury     17.1     33.0       0.0          NaN   
22      2008-12-23   Albury     20.5     31.8       0.0          NaN   
23      2008-12-24   Albury     15.3     30.9       0.0          NaN   
24      2008-12-25   Albury     12.6     32.4       0.0          NaN   
25      2008-12-26   Albury     16.2     33.9       0.0          NaN   
26      2008-12-27   Albury     16.9     33.0       0.0          NaN   
27      2008-12-28   Albury     20.1     32.7       0.0          NaN   
28      2008-12-29   Albury     19.7     27.2       0.0          NaN   
29      2008-12-30   Albury     12.5     24.2       1.2          NaN   
...            ...      ...      ...      ...       ...          ...   
145430  2017-05-27    Uluru      9.3     28.0       0.0          NaN   
145431  2017-05-28    Uluru      8.0     24.6       0.0          NaN   
145432  2017-05-29    Uluru     12.7     22.2       0.0          NaN   
145433  2017-05-30    Uluru      9.4     22.7       0.0          NaN   
145434  2017-05-31    Uluru      5.4     20.5       0.0          NaN   
145435  2017-06-01    Uluru      5.6     19.4       0.0          NaN   
145436  2017-06-02    Uluru      1.5     19.2       0.0          NaN   
145437  2017-06-03    Uluru      3.8     19.8       0.0          NaN   
145438  2017-06-04    Uluru      4.5     18.8       0.0          NaN   
145439  2017-06-05    Uluru      4.9     20.7       0.0          NaN   
145440  2017-06-06    Uluru      1.2     20.8       0.0          NaN   
145441  2017-06-07    Uluru      0.5     21.7       0.0          NaN   
145442  2017-06-08    Uluru      4.0     20.0       0.0          NaN   
145443  2017-06-09    Uluru      3.4     19.8       0.0          NaN   
145444  2017-06-10    Uluru      3.2     18.6       0.0          NaN   
145445  2017-06-11    Uluru      2.4     19.1       0.0          NaN   
145446  2017-06-12    Uluru      5.1     19.7       0.0          NaN   
145447  2017-06-13    Uluru      2.5     21.2       0.0          NaN   
145448  2017-06-14    Uluru      2.3     21.4       0.0          NaN   
145449  2017-06-15    Uluru      2.6     22.5       0.0          NaN   
145450  2017-06-16    Uluru      5.2     24.3       0.0          NaN   
145451  2017-06-17    Uluru      6.4     23.4       0.0          NaN   
145452  2017-06-18    Uluru      8.0     20.7       0.0          NaN   
145453  2017-06-19    Uluru      7.4     20.6       0.

In [4]:
weather.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2  2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3  2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4  2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          W      ...             22.0   
1         WNW           44.0        NNW      ...             25.0   
2         WSW           46.0          W      ...             30.0   
3          NE           24.0         SE      ...             16.0   
4           W           41.0        ENE      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

In [5]:
weather.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  143975.000000  144199.000000  142199.000000  82670.000000   
mean       12.194034      23.221348       2.360918      5.468232   
std         6.398495       7.119049       8.478060      4.193704   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.900000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  75625.000000  135197.000000  143693.000000  142398.000000   
mean       7.611178      40.035230      14.043426      18.662657   
std        3.785483      13.607062       8.915375       8.809800   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.800000      31.000000       7.000000      13.000000   
50%        8.400000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm   Pressure9am    Pressure3pm  \
count  142806.000000  140953.000000  130395.00000  130432.000000   
mean       68.880831      51.539116    1017.64994    1015.255889   
std        19.029164      20.795902       7.10653       7.037414   
min         0.000000       0.000000     980.50000     977.100000   
25%        57.000000      37.000000    1012.90000    1010.400000   
50%        70.000000      52.000000    1017.60000    1015.200000   
75%        83.000000      66.000000    1022.40000    1020.000000   
max       100.000000     100.000000    1041.00000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am       Temp3pm        RISK_MM  
count  89572.000000  86102.000000  143693.000000  141851.00000  142193.000000  
mean       4.447461      4.509930      16.990631      21.68339       2.360682  
std        2.887159      2.720357       6.488753       6.93665       8.477969  
min        0.000000      0.000000      -7.200000      -5.40000       0.000000  
25%        1.000000      2.000000      12.300000      16.60000       0.000000  
50%        5.000000      5.000000      16.700000      21.10000       0.000000  
75%        7.000000      7.000000      21.600000      26.40000       0.800000  
max        9.000000      9.000000      40.200000      46.70000     371.000000

## 1. Missing Value

In [6]:
np.sum(weather.isnull())

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RISK_MM           3267
RainTomorrow      3267
dtype: int64

In [16]:
weather['MinTemp']=weather['MinTemp'].fillna((weather['MinTemp'].median()))
weather['MaxTemp']=weather['MaxTemp'].fillna((weather['MaxTemp'].median()))
weather['Rainfall']=weather['Rainfall'].fillna((weather['Rainfall'].median()))
weather['Evaporation']=weather['Evaporation'].fillna((weather['Evaporation'].median()))
weather['Sunshine']=weather['Sunshine'].fillna((weather['Sunshine'].median()))
weather['WindGustSpeed']=weather['WindGustSpeed'].fillna((weather['WindGustSpeed'].median()))
weather['WindSpeed9am']=weather['WindSpeed9am'].fillna((weather['WindSpeed9am'].median()))
weather['WindSpeed3pm']=weather['WindSpeed3pm'].fillna((weather['WindSpeed3pm'].median()))
weather['Humidity9am']=weather['Humidity9am'].fillna((weather['Humidity9am'].median()))
weather['Humidity3pm']=weather['Humidity3pm'].fillna((weather['Humidity3pm'].median()))
weather['Pressure9am']=weather['Pressure9am'].fillna((weather['Pressure9am'].median()))
weather['Pressure3pm']=weather['Pressure3pm'].fillna((weather['Pressure3pm'].median()))
weather['Cloud9am']=weather['Cloud9am'].fillna((weather['Cloud9am'].median()))
weather['Cloud3pm']=weather['Cloud3pm'].fillna((weather['Cloud3pm'].median()))
weather['Temp9am']=weather['Temp9am'].fillna((weather['Temp9am'].median()))
weather['Temp3pm']=weather['Temp3pm'].fillna((weather['Temp3pm'].median()))
weather['RISK_MM']=weather['RISK_MM'].fillna((weather['RISK_MM'].median()))
np.sum(weather.isnull())

Date                0
Location            0
MinTemp             0
MaxTemp             0
Rainfall            0
Evaporation         0
Sunshine            0
WindGustDir         0
WindGustSpeed       0
WindDir9am          0
WindDir3pm          0
WindSpeed9am        0
WindSpeed3pm        0
Humidity9am         0
Humidity3pm         0
Pressure9am         0
Pressure3pm         0
Cloud9am            0
Cloud3pm            0
Temp9am             0
Temp3pm             0
RainToday           0
RISK_MM             0
RainTomorrow     3267
dtype: int64

In [9]:
((weather['WindGustDir'].mode()))

0    W
dtype: object

In [10]:
((weather['WindDir9am'].mode()))

0    N
dtype: object

In [11]:
((weather['WindDir3pm'].mode()))

0    SE
dtype: object

In [12]:
((weather['RainToday'].mode()))

0    No
dtype: object

In [17]:
((weather['RainTomorrow'].mode()))

0    No
dtype: object

In [13]:
from scipy.stats import mode

In [19]:
weather['WindGustDir']=weather['WindGustDir'].fillna(weather['WindGustDir']).dropna().mode()[0]
weather['WindDir9am']=weather['WindDir9am'].fillna(weather['WindDir9am']).dropna().mode()[0]
weather['WindDir3pm']=weather['WindDir3pm'].fillna(weather['WindDir3pm']).dropna().mode()[0]
weather['RainToday']=weather['RainToday'].fillna(weather['RainToday']).dropna().mode()[0]
weather['RainTomorrow']=weather['RainTomorrow'].fillna(weather['RainTomorrow']).dropna().mode()[0]
weather.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [22]:
weather_tanpa_missing_value= weather
print( weather_tanpa_missing_value)

              Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          4.8   
1       2008-12-02   Albury      7.4     25.1       0.0          4.8   
2       2008-12-03   Albury     12.9     25.7       0.0          4.8   
3       2008-12-04   Albury      9.2     28.0       0.0          4.8   
4       2008-12-05   Albury     17.5     32.3       1.0          4.8   
5       2008-12-06   Albury     14.6     29.7       0.2          4.8   
6       2008-12-07   Albury     14.3     25.0       0.0          4.8   
7       2008-12-08   Albury      7.7     26.7       0.0          4.8   
8       2008-12-09   Albury      9.7     31.9       0.0          4.8   
9       2008-12-10   Albury     13.1     30.1       1.4          4.8   
10      2008-12-11   Albury     13.4     30.4       0.0          4.8   
11      2008-12-12   Albury     15.9     21.7       2.2          4.8   
12      2008-12-13   Albury     15.9     18.6      15.6         

## 2. Missing Value dan Outlier

In [30]:
from scipy import stats
weather1=weather_tanpa_missing_value.drop(['WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow'], 1)
z = np.abs(stats.zscore(weather1._get_numeric_data()))
print(z)

[[0.18975691 0.0445749  0.20358073 ... 0.01350553 0.0191346  0.27506582]
 [0.75278601 0.26579424 0.27509664 ... 0.03301131 0.3840643  0.27506582]
 [0.11121166 0.35044037 0.27509664 ... 0.62222462 0.22349523 0.27506582]
 ...
 [1.06696699 0.51973264 0.27509664 ... 0.69575252 0.64681369 0.27506582]
 [0.68994982 0.53384032 0.27509664 ... 0.29260657 0.6322165  0.27506582]
 [0.42539264 0.08689797 0.27509664 ... 0.30811219 0.11224009 0.27506582]]


In [31]:
weather_tanpa_missing_value_dan_outlier = weather_tanpa_missing_value[(z < 3).all(axis=1)]
print(weather_tanpa_missing_value_dan_outlier.shape)

(134646, 24)


In [32]:
weather_tanpa_missing_value_dan_outlier.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          4.8       8.4   
1  2008-12-02   Albury      7.4     25.1       0.0          4.8       8.4   
2  2008-12-03   Albury     12.9     25.7       0.0          4.8       8.4   
3  2008-12-04   Albury      9.2     28.0       0.0          4.8       8.4   
4  2008-12-05   Albury     17.5     32.3       1.0          4.8       8.4   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          N      ...             22.0   
1           W           44.0          N      ...             25.0   
2           W           46.0          N      ...             30.0   
3           W           24.0          N      ...             16.0   
4           W           41.0          N      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       5.0     16.9     21.8         No   
1       1010.6       1007.8       5.0       5.0     17.2     24.3         No   
2       1007.6       1008.7       5.0       2.0     21.0     23.2         No   
3       1017.6       1012.8       5.0       5.0     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

## Transformasi Data

In [37]:
weather2= weather_tanpa_missing_value_dan_outlier.drop(['Date', 'Location', 'WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday', 'RainTomorrow'], 1)
from sklearn.preprocessing import normalize
norm = normalize(weather2, norm ='l2')
norm = pd.DataFrame(norm)
norm

0         1         2         3         4         5         6   \
0       0.009382  0.016034  0.000420  0.003361  0.005881  0.030808  0.014004   
1       0.005176  0.017558  0.000000  0.003358  0.005876  0.030778  0.002798   
2       0.009031  0.017993  0.000000  0.003361  0.005881  0.032205  0.013302   
3       0.006400  0.019478  0.000000  0.003339  0.005844  0.016696  0.007652   
4       0.012233  0.022579  0.000699  0.003355  0.005872  0.028660  0.004893   
5       0.010223  0.020797  0.000140  0.003361  0.005882  0.039213  0.013304   
6       0.010002  0.017487  0.000000  0.003357  0.005876  0.034974  0.013990   
7       0.005374  0.018633  0.000000  0.003350  0.005862  0.024425  0.004187   
8       0.009187  0.021110  0.000982  0.003366  0.005891  0.019637  0.010520   
9       0.009364  0.021244  0.000000  0.003354  0.005870  0.020965  0.011880   
10      0.011108  0.015160  0.001537  0.003353  0.005869  0.021658  0.010479   
11      0.008873  0.014789  0.002535  0.003380  0.005915  0.030986  0.016901   
12      0.005874  0.017201  0.000000  0.003356  0.005874  0.027270  0.002797   
13      0.006834  0.019318  0.000000  0.003347  0.005858  0.034870  0.009066   
14      0.009826  0.014564  0.000000  0.003345  0.005854  0.015331  0.007665   
15      0.009468  0.016060  0.011782  0.003366  0.005891  0.044183  0.004208   
16      0.007830  0.015731  0.007411  0.003356  0.005873  0.030063  0.016779   
17      0.006797  0.017756  0.000000  0.003329  0.005826  0.018034  0.011791   
18      0.007982  0.020337  0.000000  0.003332  0.005830  0.016658  0.006247   
19      0.011938  0.023039  0.000000  0.003351  0.005865  0.030021  0.011869   
20      0.014367  0.022286  0.000000  0.003364  0.005887  0.028733  0.013315   
21      0.010696  0.021602  0.000000  0.003356  0.005872  0.023070  0.004195   
22      0.008792  0.022607  0.000000  0.003349  0.005861  0.030003  0.002791   
23      0.011331  0.023710  0.000000  0.003357  0.005875  0.024480  0.006295   
24      0.011860  0.023159  0.000000  0.003369  0.005895  0.040002  0.000000   
25      0.014129  0.022986  0.000000  0.003374  0.005905  0.033741  0.009138   
26      0.013838  0.019106  0.000000  0.003372  0.005900  0.032312  0.013346   
27      0.008766  0.016970  0.000841  0.003366  0.005890  0.035062  0.007714   
28      0.008424  0.017128  0.000562  0.003370  0.005897  0.027377  0.011934   
29      0.007941  0.018624  0.000000  0.003373  0.005903  0.039356  0.013353   
...          ...       ...       ...       ...       ...       ...       ...   
134616  0.006450  0.019420  0.000000  0.003329  0.005826  0.019420  0.004161   
134617  0.005537  0.017026  0.000000  0.003322  0.005814  0.022840  0.007613   
134618  0.008762  0.015315  0.000000  0.003311  0.005795  0.025526  0.013108   
134619  0.006472  0.015629  0.000000  0.003305  0.005783  0.024097  0.008950   
134620  0.003710  0.014083  0.000000  0.003297  0.005770  0.031600  0.013739   
134621  0.003843  0.013314  0.000000  0.003294  0.005765  0.029511  0.015099   
134622  0.001030  0.013181  0.000000  0.003295  0.005767  0.025401  0.011671   
134623  0.002615  0.013623  0.000000  0.003303  0.005780  0.026833  0.013073   
134624  0.003102  0.012959  0.000000  0.003309  0.005790  0.021369  0.008961   
134625  0.003375  0.014257  0.000000  0.003306  0.005785  0.025483  0.011708   
134626  0.000825  0.014293  0.000000  0.003298  0.005772  0.029549  0.008933   
134627  0.000344  0.014924  0.000000  0.003301  0.005777  0.029574  0.008941   
134628  0.002745  0.013727  0.000000  0.003294  0.005765  0.026767  0.008922   
134629  0.002331  0.013573  0.000000  0.003290  0.005758  0.029477  0.013025   
134630  0.002195  0.012757  0.000000  0.003292  0.005761  0.031551  0.010288   
134631  0.001648  0.013116  0.000000  0.003296  0.005768  0.022661  0.011674   
134632  0.003505  0.013538  0.000000  0.003298  0.005772  0.031611  0.008933   
134633  0.001722  0.014598  0.000000  0.003305  0.005784  0.024101  0.011706   
134634  0.0015

## 4. feature Selection (Mencari Skor)

In [42]:
from sklearn.feature_selection import SelectKBest, chi2, f_regression # metode feature selection, chi2 untuk klasifikasi
weather3= weather_tanpa_missing_value_dan_outlier.drop(['Date', 'Location'], 1)
x = weather3.drop(columns=['RainTomorrow'])
y = weather_tanpa_missing_value_dan_outlier[['RainTomorrow']]
selector = SelectKBest (f_regression, k='all').fit(x,y) #memunculkan 1 variabel prediktor terpenting
X_new = selector.transform(x)
scores = selector.scores_
scores

ValueError: could not convert string to float: 'W'