# Transformasi Data

In [1]:
import pandas as pd
import numpy as np

In [14]:
#import datase
pcademo=pd.read_csv("pcademo.csv", sep=',')
x=pcademo.iloc[0:51,1:20]
x.tail()

Census Resident Total Population - Apr-1-2000  \
46                                      7078515.0   
47                                      5894121.0   
48                                      1808344.0   
49                                      5363675.0   
50                                       493782.0   

    Resident Total Population Estimate - Jul-1-2000  \
46                                        7104016.0   
47                                        5908372.0   
48                                        1807099.0   
49                                        5372243.0   
50                                         494001.0   

    Resident Total Population Estimate - Jul-1-2001  \
46                                        7187734.0   
47                                        5987973.0   
48                                        1801916.0   
49                                        5401906.0   
50                                         494423.0   

    Net Domestic Migration - Jul-1-2000  Net Domestic Migration - Jul-1-2001  \
46                               8119.0                              18299.0   
47                                425.0                              21995.0   
48                              -1411.0                              -4442.0   
49                               1536.0                               2974.0   
50                               -399.0                              -2041.0   

    Federal/Civilian Movement from Abroad - Jul-1-2000  \
46                                              232.0    
47                                               83.0    
48                                                0.0    
49                                                0.0    
50                                                5.0    

    Federal/Civilian Movement from Abroad - Jul-1-2001  \
46                                            -1212.0    
47                                             -444.0    
48                                               -1.0    
49                                               -5.0    
50                                              -27.0    

    Net International Migration - Jul-1-2000  \
46                                    5721.0   
47                                    5249.0   
48                                     129.0   
49                                    1571.0   
50                                     100.0   

    Net International Migration - Jul-1-2001  Period Births - Jul-1-2000  \
46                                   22619.0                     24352.0   
47                                   22052.0                     19388.0   
48                                     491.0                      5041.0   
49                                    6056.0                     16696.0   
50                                     390.0                      1480.0   

    Period Births - Jul-1-2001  Period Deaths - Jul-1-2000  \
46                    100188.0                     13158.0   
47                     80339.0                     10365.0   
48                     20436.0                      4937.0   
49                     68631.0                     11058.0   
50                      6130.0                       976.0   

    Period Deaths - Jul-1-2001  \
46                     57337.0   
47                     44681.0   
48                     21435.0   
49                     47276.0   
50                      3980.0   

    Resident Under 65 Population Estimate - Jul-1-2000  \
46                                          6308235.0    
47                                          5244172.0    
48                                          1530334.0    
49                                          4669153.0    
50                                           436178.0    

    Resident Under 65 Population Estimate - Jul-1-2001  \
46                                          6380181.0    
47                                          5317341.0  

In [19]:
#normalization
from sklearn.preprocessing import normalize
xnorm=normalize(x,norm='l2') #default norm 12, other are L1 and max
xnorm=pd.DataFrame(xnorm)
xnorm.tail()
# rentangnya antara 0 sampai 1

0         1         2         3         4         5             6   \
46  0.462700  0.464367  0.469840  0.000531  0.001196  0.000015 -7.922467e-05   
47  0.462826  0.463946  0.470196  0.000033  0.001727  0.000007 -3.486439e-05   
48  0.473139  0.472813  0.471457 -0.000369 -0.001162  0.000000 -2.616422e-07   
49  0.467409  0.468156  0.470741  0.000134  0.000259  0.000000 -4.357173e-07   
50  0.466655  0.466862  0.467261 -0.000377 -0.001929  0.000005 -2.551669e-05   

          7         8         9         10        11        12        13  \
46  0.000374  0.001479  0.001592  0.006549  0.000860  0.003748  0.412350   
47  0.000412  0.001732  0.001522  0.006308  0.000814  0.003509  0.411790   
48  0.000034  0.000128  0.001319  0.005347  0.001292  0.005608  0.400400   
49  0.000137  0.000528  0.001455  0.005981  0.000964  0.004120  0.406886   
50  0.000095  0.000369  0.001399  0.005793  0.000922  0.003761  0.412216   

          14        15        16        17        18  
46  0.417053  0.052018  0.052787  0.000015  0.000076  
47  0.417536  0.052155  0.052660 -0.000042  0.000027  
48  0.399360  0.072413  0.072097 -0.000018 -0.000061  
49  0.409435  0.061270  0.061306 -0.000015 -0.000062  
50  0.412252  0.054646  0.055008  0.000009 -0.000047

In [21]:
#minmax
#dimana rentang nilai bisa kita tentuin sendiri
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(-2,1))# nilainya antara -2 sampai 1
scaler.fit(x)
x_scaled=scaler.transform(x) #x_scaled : nama
x_scaled=pd.DataFrame(x_scaled)
x_scaled.tail()

0         1         2         3         4         5         6   \
46 -1.408165 -1.408172 -1.409530  0.081289 -0.367728  0.071429 -1.399604   
47 -1.514618 -1.515224 -1.515371 -0.221537 -0.340696 -1.258929  0.122193   
48 -1.881847 -1.882432 -1.884656 -0.293800 -0.534054 -2.000000  1.000000   
49 -1.562294 -1.563227 -1.567072 -0.177810 -0.479814 -2.000000  0.992074   
50 -2.000000 -2.000000 -2.000000 -0.253969 -0.516493 -1.955357  0.948481   

          7         8         9         10        11        12        13  \
46 -1.764982 -1.754108 -1.465178 -1.461725 -1.298420 -1.286696 -1.411887   
47 -1.784717 -1.760374 -1.581253 -1.575317 -1.455445 -1.452681 -1.518458   
48 -1.998787 -1.998641 -1.916732 -1.918130 -1.760612 -1.757554 -1.890415   
49 -1.938496 -1.937143 -1.644201 -1.642319 -1.416484 -1.418647 -1.576049   
50 -2.000000 -1.999757 -2.000000 -2.000000 -1.983302 -1.986478 -2.000000   

          14        15        16        17        18  
46 -1.413594 -1.362311 -1.361172 -0.408483 -0.187941  
47 -1.518449 -1.472741 -1.474666 -1.740267 -0.633895  
48 -1.892451 -1.797900 -1.802143 -0.934922 -0.944595  
49 -1.579511 -1.440103 -1.447420 -1.126671 -1.208039  
50 -2.000000 -1.981649 -1.982303 -0.802440 -0.845736

In [23]:
#3sigmoid
xsigmoidal=(1-2.718281828**(-xnorm))/(1+2.718281828**(-xnorm)) #nilai eksponensial =2.718281828
xsigmoidal=pd.DataFrame(xsigmoidal) 
xsigmoidal.tail()

0         1         2         3         4         5             6   \
46  0.227309  0.228099  0.230692  0.000265  0.000598  0.000008 -3.961233e-05   
47  0.227369  0.227899  0.230860  0.000017  0.000864  0.000003 -1.743220e-05   
48  0.232253  0.232099  0.231457 -0.000185 -0.000581  0.000000 -1.308211e-07   
49  0.229541  0.229894  0.231118  0.000067  0.000130  0.000000 -2.178586e-07   
50  0.229183  0.229282  0.229470 -0.000189 -0.000964  0.000002 -1.275835e-05   

          7         8         9         10        11        12        13  \
46  0.000187  0.000739  0.000796  0.003274  0.000430  0.001874  0.203302   
47  0.000206  0.000866  0.000761  0.003154  0.000407  0.001754  0.203034   
48  0.000017  0.000064  0.000659  0.002673  0.000646  0.002804  0.197567   
49  0.000068  0.000264  0.000727  0.002990  0.000482  0.002060  0.200682   
50  0.000047  0.000184  0.000699  0.002897  0.000461  0.001881  0.203238   

          14        15        16        17        18  
46  0.205555  0.026003  0.026387  0.000008  0.000038  
47  0.205787  0.026072  0.026324 -0.000021  0.000013  
48  0.197068  0.036191  0.036033 -0.000009 -0.000030  
49  0.201905  0.030625  0.030643 -0.000008 -0.000031  
50  0.203256  0.027316  0.027497  0.000004 -0.000024

In [25]:
# decimal scalling
xdecimal=x/(10**3)# 10** i, i ditentukan peneliti
xdecimal=pd.DataFrame(xdecimal)
xdecimal.tail()

Census Resident Total Population - Apr-1-2000  \
46                                       7078.515   
47                                       5894.121   
48                                       1808.344   
49                                       5363.675   
50                                        493.782   

    Resident Total Population Estimate - Jul-1-2000  \
46                                         7104.016   
47                                         5908.372   
48                                         1807.099   
49                                         5372.243   
50                                          494.001   

    Resident Total Population Estimate - Jul-1-2001  \
46                                         7187.734   
47                                         5987.973   
48                                         1801.916   
49                                         5401.906   
50                                          494.423   

    Net Domestic Migration - Jul-1-2000  Net Domestic Migration - Jul-1-2001  \
46                                8.119                               18.299   
47                                0.425                               21.995   
48                               -1.411                               -4.442   
49                                1.536                                2.974   
50                               -0.399                               -2.041   

    Federal/Civilian Movement from Abroad - Jul-1-2000  \
46                                              0.232    
47                                              0.083    
48                                              0.000    
49                                              0.000    
50                                              0.005    

    Federal/Civilian Movement from Abroad - Jul-1-2001  \
46                                             -1.212    
47                                             -0.444    
48                                             -0.001    
49                                             -0.005    
50                                             -0.027    

    Net International Migration - Jul-1-2000  \
46                                     5.721   
47                                     5.249   
48                                     0.129   
49                                     1.571   
50                                     0.100   

    Net International Migration - Jul-1-2001  Period Births - Jul-1-2000  \
46                                    22.619                      24.352   
47                                    22.052                      19.388   
48                                     0.491                       5.041   
49                                     6.056                      16.696   
50                                     0.390                       1.480   

    Period Births - Jul-1-2001  Period Deaths - Jul-1-2000  \
46                     100.188                      13.158   
47                      80.339                      10.365   
48                      20.436                       4.937   
49                      68.631                      11.058   
50                       6.130                       0.976   

    Period Deaths - Jul-1-2001  \
46                      57.337   
47                      44.681   
48                      21.435   
49                      47.276   
50                       3.980   

    Resident Under 65 Population Estimate - Jul-1-2000  \
46                                           6308.235    
47                                           5244.172    
48                                           1530.334    
49                                           4669.153    
50                                            436.178    

    Resident Under 65 Population Estimate - Jul-1-2001  \
46                                           6380.181    
47                                           5317.341  

In [26]:
#softmax
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)
xsoft=softmax(xnorm)
xsoft=pd.DataFrame(xsoft)
print(xsoft)
#

          0         1         2         3         4         5         6   \
0   0.019651  0.019641  0.019595  0.019605  0.019589  0.019608  0.019608   
1   0.019390  0.019381  0.019412  0.019585  0.019590  0.019608  0.019606   
2   0.019521  0.019563  0.019742  0.019638  0.019739  0.019608  0.019608   
3   0.019663  0.019660  0.019636  0.019611  0.019609  0.019608  0.019608   
4   0.019514  0.019529  0.019590  0.019603  0.019587  0.019608  0.019608   
5   0.019450  0.019477  0.019601  0.019626  0.019691  0.019608  0.019608   
6   0.019664  0.019657  0.019625  0.019604  0.019583  0.019608  0.019608   
7   0.019598  0.019610  0.019653  0.019621  0.019655  0.019608  0.019608   
8   0.019645  0.019611  0.019550  0.019570  0.019534  0.019608  0.019608   
9   0.019685  0.019708  0.019834  0.019626  0.019724  0.019608  0.019608   
10  0.019457  0.019486  0.019582  0.019628  0.019670  0.019608  0.019608   
11  0.019636  0.019623  0.019642  0.019584  0.019582  0.019608  0.019606   
12  0.019525

In [36]:
# feature selection (mencari skor)
from sklearn.feature_selection import SelectKBest, chi2, f_regression
Xx = x.iloc[0:51,2:20]
y = x.iloc[0:51,1]
selector = SelectKBest (f_regression, k="all").fit(Xx,y)
X_new = selector.transform(Xx)
scores = selector.scores_
scores
#semakin tinggi skore, maka variabel semakin baik untuk model

array([5.61375136e+05, 3.36516052e+00, 1.44451214e+00, 4.99675650e+01,
       4.33492917e+01, 2.71500530e+02, 2.81466705e+02, 3.05153091e+03,
       3.01376496e+03, 1.09412350e+03, 1.02966997e+03, 4.78297078e+04,
       4.08507686e+04, 8.40708042e+02, 8.74017871e+02, 1.53597567e+00,
       3.97449012e+00])

In [37]:
X_new

array([[ 4.4643560e+06, -1.4340000e+03, -7.9660000e+03,  1.7000000e+01,
        -9.8000000e+01,  7.1400000e+02,  3.0790000e+03,  1.5812000e+04,
         6.4319000e+04,  1.0622000e+04,  4.5912000e+04,  3.8705980e+06,
         3.8804760e+06,  5.8089500e+05,  5.8388000e+05, -9.4000000e+01,
        -5.5900000e+02],
       [ 6.3489200e+05, -1.6110000e+03, -1.0910000e+03,  2.8000000e+01,
        -1.5200000e+02,  3.7900000e+02,  1.3300000e+03,  2.4960000e+03,
         1.0128000e+04,  6.7900000e+02,  2.9490000e+03,  5.9164400e+05,
         5.9803600e+05,  3.5957000e+04,  3.6856000e+04,  5.6000000e+01,
         2.5000000e+01],
       [ 5.3073310e+06,  1.7259000e+04,  7.5633000e+04,  3.7000000e+01,
        -1.8000000e+02,  6.1240000e+03,  2.2794000e+04,  2.0486000e+04,
         8.4295000e+04,  9.4860000e+03,  4.1217000e+04,  4.4921860e+06,
         4.6149120e+06,  6.7308800e+05,  6.9241900e+05,  2.2200000e+02,
         7.3200000e+02],
       [ 2.6920900e+06,  1.1010000e+03,  9.6400000e+02,  6.00

In [38]:
# feature selection (mencari skor)
from sklearn.feature_selection import SelectKBest, chi2, f_regression # metode feature selection, chi2 untuk klasifikasi
Xx = x.iloc[0:51,2:20]
y = x.iloc[0:51,1]
selector = SelectKBest (f_regression, k=1).fit(Xx,y) #memunculkan 1 variabel prediktor terpenting
X_new = selector.transform(Xx)
scores = selector.scores_
scores

array([5.61375136e+05, 3.36516052e+00, 1.44451214e+00, 4.99675650e+01,
       4.33492917e+01, 2.71500530e+02, 2.81466705e+02, 3.05153091e+03,
       3.01376496e+03, 1.09412350e+03, 1.02966997e+03, 4.78297078e+04,
       4.08507686e+04, 8.40708042e+02, 8.74017871e+02, 1.53597567e+00,
       3.97449012e+00])

In [39]:
X_new

array([[ 4464356.],
       [  634892.],
       [ 5307331.],
       [ 2692090.],
       [34501130.],
       [ 4417714.],
       [ 3425074.],
       [  796165.],
       [  571822.],
       [16396515.],
       [ 8383915.],
       [ 1224398.],
       [ 1321006.],
       [12482301.],
       [ 6114745.],
       [ 2923179.],
       [ 2694641.],
       [ 4065556.],
       [ 4465430.],
       [ 1286670.],
       [ 5375156.],
       [ 6379304.],
       [ 9990817.],
       [ 4972294.],
       [ 2858029.],
       [ 5629707.],
       [  904433.],
       [ 1713235.],
       [ 2106074.],
       [ 1259181.],
       [ 8484431.],
       [ 1829146.],
       [19011378.],
       [ 8186268.],
       [  634448.],
       [11373541.],
       [ 3460097.],
       [ 3472867.],
       [12287150.],
       [ 1058920.],
       [ 4063011.],
       [  756600.],
       [ 5740021.],
       [21325018.],
       [ 2269789.],
       [  613090.],
       [ 7187734.],
       [ 5987973.],
       [ 1801916.],
       [ 5401906.],
