# Tugas 2
## Pre Processing Data
### Cleaning Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
weather = pd.read_csv("D:\statistika\SEMESTER 6\DATMIN\Pre Processing Data\weatherAUS_tugas2.csv", sep=';')

In [3]:
weather

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       01/12/2008   Albury     13.4     22.9       0.6          NaN   
1       02/12/2008   Albury      7.4     25.1       0.0          NaN   
2       03/12/2008   Albury     12.9     25.7       0.0          NaN   
3       04/12/2008   Albury      9.2     28.0       0.0          NaN   
4       05/12/2008   Albury     17.5     32.3       1.0          NaN   
5       06/12/2008   Albury     14.6     29.7       0.2          NaN   
6       07/12/2008   Albury     14.3     25.0       0.0          NaN   
7       08/12/2008   Albury      7.7     26.7       0.0          NaN   
8       09/12/2008   Albury      9.7     31.9       0.0          NaN   
9       10/12/2008   Albury     13.1     30.1       1.4          NaN   
10      11/12/2008   Albury     13.4     30.4       0.0          NaN   
11      12/12/2008   Albury     15.9     21.7       2.2          NaN   
12      13/12/2008   Albury     15.9     18.6      15.6          NaN   
13      14/12/2008   Albury     12.6     21.0       3.6          NaN   
14      16/12/2008   Albury      9.8     27.7       NaN          NaN   
15      17/12/2008   Albury     14.1     20.9       0.0          NaN   
16      18/12/2008   Albury     13.5     22.9      16.8          NaN   
17      19/12/2008   Albury     11.2     22.5      10.6          NaN   
18      20/12/2008   Albury      9.8     25.6       0.0          NaN   
19      21/12/2008   Albury     11.5     29.3       0.0          NaN   
20      22/12/2008   Albury     17.1     33.0       0.0          NaN   
21      23/12/2008   Albury     20.5     31.8       0.0          NaN   
22      24/12/2008   Albury     15.3     30.9       0.0          NaN   
23      25/12/2008   Albury     12.6     32.4       0.0          NaN   
24      26/12/2008   Albury     16.2     33.9       0.0          NaN   
25      27/12/2008   Albury     16.9     33.0       0.0          NaN   
26      28/12/2008   Albury     20.1     32.7       0.0          NaN   
27      29/12/2008   Albury     19.7     27.2       0.0          NaN   
28      30/12/2008   Albury     12.5     24.2       1.2          NaN   
29      31/12/2008   Albury     12.0     24.4       0.8          NaN   
...            ...      ...      ...      ...       ...          ...   
142163  26/05/2017    Uluru     14.3     27.6       0.4          NaN   
142164  27/05/2017    Uluru      9.3     28.0       0.0          NaN   
142165  28/05/2017    Uluru      8.0     24.6       0.0          NaN   
142166  29/05/2017    Uluru     12.7     22.2       0.0          NaN   
142167  30/05/2017    Uluru      9.4     22.7       0.0          NaN   
142168  31/05/2017    Uluru      5.4     20.5       0.0          NaN   
142169  01/06/2017    Uluru      5.6     19.4       0.0          NaN   
142170  02/06/2017    Uluru      1.5     19.2       0.0          NaN   
142171  03/06/2017    Uluru      3.8     19.8       0.0          NaN   
142172  04/06/2017    Uluru      4.5     18.8       0.0          NaN   
142173  05/06/2017    Uluru      4.9     20.7       0.0          NaN   
142174  06/06/2017    Uluru      1.2     20.8       0.0          NaN   
142175  07/06/2017    Uluru      0.5     21.7       0.0          NaN   
142176  08/06/2017    Uluru      4.0     20.0       0.0          NaN   
142177  09/06/2017    Uluru      3.4     19.8       0.0          NaN   
142178  10/06/2017    Uluru      3.2     18.6       0.0          NaN   
142179  11/06/2017    Uluru      2.4     19.1       0.0          NaN   
142180  12/06/2017    Uluru      5.1     19.7       0.0          NaN   
142181  13/06/2017    Uluru      2.5     21.2       0.0          NaN   
142182  14/06/2017    Uluru      2.3     21.4       0.0          NaN   
142183  15/06/2017    Uluru      2.6     22.5       0.0          NaN   
142184  16/06/2017    Uluru      5.2     24.3       0.0          NaN   
142185  17/06/2017    Uluru      6.4     23.4       0.0          NaN   
142186  18/06/2017    Uluru      8.0     20.7       0.

In [4]:
weather.head()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  01/12/2008   Albury     13.4     22.9       0.6          NaN       NaN   
1  02/12/2008   Albury      7.4     25.1       0.0          NaN       NaN   
2  03/12/2008   Albury     12.9     25.7       0.0          NaN       NaN   
3  04/12/2008   Albury      9.2     28.0       0.0          NaN       NaN   
4  05/12/2008   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am      ...      Humidity3pm  \
0           W           44.0          W      ...             22.0   
1         WNW           44.0        NNW      ...             25.0   
2         WSW           46.0          W      ...             30.0   
3          NE           24.0         SE      ...             16.0   
4           W           41.0        ENE      ...             33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   
2       1007.6       1008.7       NaN       2.0     21.0     23.2         No   
3       1017.6       1012.8       NaN       NaN     18.1     26.5         No   
4       1010.8       1006.0       7.0       8.0     17.8     29.7         No   

   RISK_MM  RainTomorrow  
0      0.0            No  
1      0.0            No  
2      0.0            No  
3      1.0            No  
4      0.2            No  

[5 rows x 24 columns]

In [5]:
weather.tail()

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
142188  20/06/2017    Uluru      3.5     21.8       0.0          NaN   
142189  21/06/2017    Uluru      2.8     23.4       0.0          NaN   
142190  22/06/2017    Uluru      3.6     25.3       0.0          NaN   
142191  23/06/2017    Uluru      5.4     26.9       0.0          NaN   
142192  24/06/2017    Uluru      7.8     27.0       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am      ...       \
142188       NaN           E           31.0        ESE      ...        
142189       NaN           E           31.0         SE      ...        
142190       NaN         NNW           22.0         SE      ...        
142191       NaN           N           37.0         SE      ...        
142192       NaN          SE           28.0        SSE      ...        

       Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
142188        27.0       1024.7       1021.2       NaN       NaN      9.4   
142189        24.0       1024.6       1020.3       NaN       NaN     10.1   
142190        21.0       1023.5       1019.1       NaN       NaN     10.9   
142191        24.0       1021.0       1016.8       NaN       NaN     12.5   
142192        24.0       1019.4       1016.5       3.0       2.0     15.1   

        Temp3pm  RainToday  RISK_MM  RainTomorrow  
142188     20.9         No      0.0            No  
142189     22.4         No      0.0            No  
142190     24.5         No      0.0            No  
142191     26.1         No      0.0            No  
142192     26.0         No      0.0            No  

[5 rows x 24 columns]

In [6]:
weather.describe()

MinTemp        MaxTemp       Rainfall   Evaporation  \
count  141556.000000  141871.000000  140787.000000  81350.000000   
mean       12.186400      23.226784       2.349974      5.469824   
std         6.403283       7.117618       8.465173      4.188537   
min        -8.500000      -4.800000       0.000000      0.000000   
25%         7.600000      17.900000       0.000000      2.600000   
50%        12.000000      22.600000       0.000000      4.800000   
75%        16.800000      28.200000       0.800000      7.400000   
max        33.900000      48.100000     371.000000    145.000000   

           Sunshine  WindGustSpeed   WindSpeed9am   WindSpeed3pm  \
count  74377.000000  132923.000000  140845.000000  139563.000000   
mean       7.624853      39.984292      14.001988      18.637576   
std        3.781525      13.588801       8.893337       8.803345   
min        0.000000       6.000000       0.000000       0.000000   
25%        4.900000      31.000000       7.000000      13.000000   
50%        8.500000      39.000000      13.000000      19.000000   
75%       10.600000      48.000000      19.000000      24.000000   
max       14.500000     135.000000     130.000000      87.000000   

         Humidity9am    Humidity3pm    Pressure9am    Pressure3pm  \
count  140419.000000  138583.000000  128179.000000  128212.000000   
mean       68.843810      51.482606    1017.653758    1015.258204   
std        19.051293      20.797772       7.105476       7.036677   
min         0.000000       0.000000     980.500000     977.100000   
25%        57.000000      37.000000    1012.900000    1010.400000   
50%        70.000000      52.000000    1017.600000    1015.200000   
75%        83.000000      66.000000    1022.400000    1020.000000   
max       100.000000     100.000000    1041.000000    1039.600000   

           Cloud9am      Cloud3pm        Temp9am        Temp3pm        RISK_MM  
count  88536.000000  85099.000000  141289.000000  139467.000000  142193.000000  
mean       4.437189      4.503167      16.987509      21.687235       2.360682  
std        2.887016      2.720633       6.492838       6.937594       8.477969  
min        0.000000      0.000000      -7.200000      -5.400000       0.000000  
25%        1.000000      2.000000      12.300000      16.600000       0.000000  
50%        5.000000      5.000000      16.700000      21.100000       0.000000  
75%        7.000000      7.000000      21.600000      26.400000       0.800000  
max        9.000000      9.000000      40.200000      46.700000     371.000000

In [7]:
np.sum(weather.isnull())

Date                 0
Location             0
MinTemp            637
MaxTemp            322
Rainfall          1406
Evaporation      60843
Sunshine         67816
WindGustDir       9330
WindGustSpeed     9270
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am      1348
WindSpeed3pm      2630
Humidity9am       1774
Humidity3pm       3610
Pressure9am      14014
Pressure3pm      13981
Cloud9am         53657
Cloud3pm         57094
Temp9am            904
Temp3pm           2726
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [8]:
weather['MinTemp']=weather['MinTemp'].fillna((weather['MinTemp'].median()))
weather['MaxTemp']=weather['MaxTemp'].fillna((weather['MaxTemp'].median()))
weather['Rainfall']=weather['Rainfall'].fillna((weather['Rainfall'].median()))
weather['Evaporation']=weather['Evaporation'].fillna((weather['Evaporation'].median()))
weather['Sunshine']=weather['Sunshine'].fillna((weather['Sunshine'].median()))
weather['WindGustSpeed']=weather['WindGustSpeed'].fillna((weather['WindGustSpeed'].median()))
weather['WindSpeed9am']=weather['WindSpeed9am'].fillna((weather['WindSpeed9am'].median()))
weather['WindSpeed3pm']=weather['WindSpeed3pm'].fillna((weather['WindSpeed3pm'].median()))
weather['Humidity9am']=weather['Humidity9am'].fillna((weather['Humidity9am'].median()))
weather['Humidity3pm']=weather['Humidity3pm'].fillna((weather['Humidity3pm'].median()))
weather['Pressure9am']=weather['Pressure9am'].fillna((weather['Pressure9am'].median()))
weather['Pressure3pm']=weather['Pressure3pm'].fillna((weather['Pressure3pm'].median()))
weather['Cloud9am']=weather['Cloud9am'].fillna((weather['Cloud9am'].median()))
weather['Cloud3pm']=weather['Cloud3pm'].fillna((weather['Cloud3pm'].median()))
weather['Temp9am']=weather['Temp9am'].fillna((weather['Temp9am'].median()))
weather['Temp3pm']=weather['Temp3pm'].fillna((weather['Temp3pm'].median()))
np.sum(weather.isnull())

Date                 0
Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation          0
Sunshine             0
WindGustDir       9330
WindGustSpeed        0
WindDir9am       10013
WindDir3pm        3778
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             0
Temp9am              0
Temp3pm              0
RainToday         1406
RISK_MM              0
RainTomorrow         0
dtype: int64

In [9]:
((weather['WindGustDir'].mode()))

0    W
dtype: object

In [10]:
((weather['WindDir9am'].mode()))

0    N
dtype: object

In [11]:
((weather['WindDir3pm'].mode()))

0    SE
dtype: object

In [12]:
((weather['RainToday'].mode()))

0    No
dtype: object

In [13]:
from scipy.stats import mode

In [14]:
weather['WindGustDir']=weather['WindGustDir'].fillna(weather['WindGustDir']).dropna().mode()[0]
weather['WindDir9am']=weather['WindDir9am'].fillna(weather['WindDir9am']).dropna().mode()[0]
weather['WindDir3pm']=weather['WindDir3pm'].fillna(weather['WindDir3pm']).dropna().mode()[0]
weather['RainToday']=weather['RainToday'].fillna(weather['RainToday']).dropna().mode()[0]
weather.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [15]:
# mengatasi outlier
from scipy import stats

In [16]:
weather1=weather.drop(['WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday'], 1)
z = np.abs(stats.zscore(weather1._get_numeric_data()))
print(z)

[[0.1900848  0.0457642  0.20492006 ... 0.0132383  0.01804963 0.27844993]
 [0.74904204 0.2636769  0.27612488 ... 0.0331139  0.38188612 0.27844993]
 [0.11182423 0.34806993 0.27612488 ... 0.62024188 0.22179807 0.27844993]
 ...
 [1.34382237 0.29180791 0.27612488 ... 0.94028247 0.41099304 0.27844993]
 [1.06208432 0.51685599 0.27612488 ... 0.69307069 0.64384839 0.27844993]
 [0.68643359 0.5309215  0.27612488 ... 0.29135155 0.62929493 0.27844993]]


In [17]:
weather = weather[(z < 3).all(axis=1)]
print(weather.shape)

(131648, 24)


In [18]:
# dari hasil cleaning data missing value dan outlier didapatkan data bersih sebanyak 131648 data pengamatan dan 24 kolom variabel